import Head from "next/head";
import Link from "next/link";

import { Metadata } from "next";
import Button from "~/components/ui/styled/Button";

export const metadata: Metadata = {
  title: "Ayden: Your Developer",
  description: "Generated by create-t3-app",
  icons: ["/favicon.ico"],
};
import { PortableText } from "@portabletext/react";
import blueWave from "~/assets/blue-wave.png";
import {
  getContact,
  getHero,
  getPhoto,
  getProjects,
  getServices,
  getSkills,
} from "~/sanity/sanity-utils";

import { headers } from "next/headers";
import { getServerPathname } from "~/utils/utils";
import { ProjectSchema } from "~/sanity/schemas/projects-schema";
import { RxArrowRight } from "react-icons/rx";
import Image from "next/image";
import ContactPage from "~/components/contact-page";
import Hero from "~/components/hero";
import ProjectCard from "~/components/ui/project-card";

export default async function Home() {
  const hero = await getHero();
  const services = await getServices();
  const projects = await getProjects({ showcaseOnly: true });
  const index = await getPhoto();
  const skills = await getSkills();

  return (
    <>
      <div className="bg-light-gray">
        <div className="relative flex min-h-screen flex-col justify-center">
          <div
            className="absolute right-0 top-0 h-full w-full bg-contain bg-right-bottom bg-no-repeat opacity-40 md:top-28"
            style={{
              backgroundImage: `url(${blueWave.src})`,
              filter: "saturate(70%)",
            }}
          ></div>
          <Hero hero={hero.filter((hero) => hero.pathname === "/").at(0)}>
            <Button type="link" href="/about" className="mx-auto mt-6 md:mx-0">
              Get in touch
            </Button>
          </Hero>
        </div>
        <div className="md:h-32"></div>
        <div className="flex flex-col items-center">
          <div className="flex flex-col items-start gap-3 px-8">
            <h2 className="pb-8 font-semibold">{services.headerText}</h2>
            <div className="flex flex-col flex-wrap gap-16 lg:flex-row">
              {services.services.map((service, i) => (
                <div
                  key={`${service.serviceName}${i}`}
                  className="max-w-96 w-full lg:w-72"
                >
                  <p className=" text-label">
                    {i < 10 ? "0" : ""}
                    {i + 1}
                  </p>
                  <hr className="" />
                  <p className=" pb-4 font-bold">{service.serviceName}</p>
                  <PortableText
                    value={service.serviceContent}
                    components={{
                      list: {
                        bullet: ({ children }) => (
                          <ul className="ml-4">{children}</ul>
                        ),
                      },
                    }}
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
        <div className="h-60"></div>
      </div>
      <div className="-mt-20 flex w-full justify-center">
        <div className="flex max-w-5xl flex-col gap-12 px-6">
          {projects.map((project, i) => (
            <ProjectCard project={project} key={`${project.name}${i}`} />
          ))}
          <Button type="link" href="/projects" className="mx-auto">
            View more projects
          </Button>
        </div>
      </div>
      <div className="h-40"></div>
      <Image
        src={index.image}
        width={720}
        height={720}
        alt="wave"
        className="mx-auto my-8 h-96 w-full max-w-4xl rounded-none object-cover shadow-lg md:rounded-xl"
      />
      <div className="h-48"></div>
      <div className="flex w-full flex-col items-center">
        <div className="flex w-full max-w-5xl flex-col items-start gap-3 px-8">
          <h2 className="pb-8 font-semibold">{skills.headerText}</h2>
          <div className="grid w-full grid-cols-3 justify-between md:grid-cols-6">
            {skills.skills.map((skill, i) => (
              <div
                key={`${skill.title}${i}`}
                className="my-3 flex w-20 flex-col items-center justify-center"
              >
                <Image
                  src={skill.image}
                  width={72}
                  height={72}
                  alt={skill.title}
                  className="h-[72px] w-[72px] object-contain object-center"
                />
                <p className="whitespace-nowrap pt-4 font-semibold">
                  {skill.title}
                </p>
              </div>
            ))}
          </div>
          <Button type="link" href="/about" className="mx-auto mt-6 md:mx-0">
            Learn more about me
          </Button>
        </div>
      </div>
      <div className="h-60"></div>
      <ContactPage />
    </>
  );
}
