import Head from "next/head";
import Link from "next/link";

import { Metadata } from "next";
import Button from "~/components/ui/styled/Button";

export const metadata: Metadata = {
  title: "Ayden: Your Developer",
  description: "Generated by create-t3-app",
  icons: ["/favicon.ico"],
};

import blueWave from "~/assets/blue-wave.png";

export default function Home() {
  return (
    <>
      <main className="relative">
        <div
          className="absolute right-0 top-32 h-full w-full bg-contain bg-right-bottom bg-no-repeat"
          style={{ backgroundImage: `url(${blueWave.src})` }}
        ></div>
        <div className="relative flex min-h-screen flex-col justify-center">
          <div className="container flex max-w-5xl flex-col gap-3 px-4 py-16 md:pl-16 lg:pl-36">
            <h2>I'm Ayden,</h2>
            <h1>
              Adaptive, Sharp, Delivering: <br />
              Your Full-Stack Developer
            </h1>
            <h2>
              Merging vision with action, amplifying user experiences with
              secure applications, and quantifiable ROI for you - all delivered
              in real-time. <b>Here to catalyze your success.</b>
            </h2>
            <Button>Get Started</Button>
          </div>
        </div>
      </main>
    </>
  );
}
